# Generated by Django 3.0.7 on 2020-06-17 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partyhall',
            name='nearby_trust',
        ),
        migrations.AddField(
            model_name='partyhall',
            name='nearby_trust',
            field=models.ManyToManyField(to='food.Trust'),
        ),
    ]
