# Generated by Django 3.0.7 on 2020-06-17 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_auto_20200617_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trust',
            name='mobile_no',
            field=models.CharField(max_length=10),
        ),
    ]
