# Generated by Django 3.0.7 on 2020-06-18 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_auto_20200617_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trust',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='trust',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Message', models.TextField(default=None)),
                ('Email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trustemail', to='food.Trust', to_field='email')),
                ('Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trustname', to='food.Trust', to_field='name')),
            ],
        ),
    ]
