# Generated by Django 3.0.7 on 2020-06-18 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_auto_20200618_0843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='Email',
        ),
        migrations.RemoveField(
            model_name='email',
            name='Name',
        ),
        migrations.AddField(
            model_name='email',
            name='NameAndEmail',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='trust_name_email', to='food.Trust'),
            preserve_default=False,
        ),
    ]
