# Generated by Django 3.0.7 on 2020-06-18 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0006_auto_20200618_0845'),
    ]

    operations = [
        migrations.AddField(
            model_name='partyhall',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
