# Generated by Django 3.0.7 on 2020-06-19 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0008_auto_20200618_1008'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Email',
        ),
        migrations.RemoveField(
            model_name='partyhall',
            name='slug',
        ),
    ]
